[manifest]
version = "1.0.0"
priority = 0

#World Cracker
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.GAME.hands[hand].chips = math.max(G.GAME.hands[hand].s_chips + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)'''
position = "after"
payload = '''
    if amount < 0 and #find_joker("j_qui_world_cracker") > 0 then
        local card = find_joker("j_qui_world_cracker")
        for i = 1, #card do
            G.E_MANAGER:add_event(Event({blockable = false, blocking = false, func = function()
                card_eval_status_text(card[i], 'extra', nil, nil, nil, {message = "KA-ching!"})
                return true
            end}))
            G.E_MANAGER:add_event(Event({trigger = "after", delay = 11 + i, blockable = false, blocking = false, func = function()
                ease_dollars(card[i].ability.extra.reward, true)
                return true
            end}))
        end
    end'''
match_indent = false
times = 1